### ISSUE TITLE
[EKS] [request]: Upgrade of EKS version to 1.20.10 and 1.21.3 

### ISSUE THREAD

**Issue by aupadh12** [aws/containers-roadmap#1499]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
We would like to request to upgrade the EKS version from existing 1.20.7 and 1.21.2 to 1.20.10 and 1.21.3 respectively.

**Which service(s) is this request for?**
This is for EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We noticed a bug in Kubernetes starting with version 1.20 that is causing an issue. When using the affected versions, Kubernetes stops sending events for the `Service` resources after a certain amount of time. 
See https://github.com/kubernetes/kubernetes/issues/102464  for more detailed information on the bug.
This bug is fixed in versions 1.20.10 and 1.21.3. However, EKS is currently at 1.20.7 version and 1.21.2  so the current version of EKS does not have the fix. We are not yet allowed to go on to 1.21 as per company policy so the latest which we have is 1.20.7. 

**Are you currently working around this issue?**
Currently we are restarting the operator every 25 min since we have noticed the issue if the operator keeps running from 30 min to 2 hrs.

**Comment by LEDfan** [comment]
I think EKS updated the kubernetes versions to 1.20.7 and 1.21.5: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html . This should include a fix for the described problem.

**Comment by stevehipwell** [comment]
@LEDfan I might be misreading this, but the EKS v1.20 version hasn't been updated as it was v1.20.7 when this bug was reported and is still the same version?

**Comment by LEDfan** [comment]
Hi @stevehipwell thanks for the heads-up, you are completely right, I messed up some versions. So v1.20 hasn't been updated. Version 1.21 has been updated to 1.21.5, which should fix the issue mentioned above. (see https://github.com/awsdocs/amazon-eks-user-guide/commit/dbca3fb933fcaf468b0f7441464f7fb6d64b02c1#diff-a7c93dd2867c005629f109bf0c19b25cedc17ecc732d860cfe4bc425b7d220b8)

**Comment by aupadh12** [comment]
Hello Everyone,

The EKS 1.21 is now updated to 1.21.5 and this solves this issue.
Closing this issue now.

**Comment by stevehipwell** [comment]
@aupadh12 is it fixed for v1.20 too? If not I don't think this issue should be closed.

**Comment by aupadh12** [comment]
@stevehipwell This is not fixed for v1.20. Reopening the issue.

**Comment by sidewinder12s** [comment]
Seems like this can be closed since 1.20 is no longer supported.
