### ISSUE TITLE
[EKS] [EFS CSI driver add-on]: deleteAccessPointRootDir flag not working

### ISSUE THREAD

**Issue by kordian2k** [aws/containers-roadmap#2120]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

The EFS CSI driver add-on allows to set the configuration flag `deleteAccessPointRootDir`. If set to `true` it should automatically delete files on EFS (not only the access points) once the corresponding `PVC` is removed. However, the files are not deleted. Moreover, the add-on does not behave like the corresponding helm chart with the `controller.deleteAccessPointRootDir=true` option set.

In particular, the `efs-plugin` container within the `efs-csi-controller` pod starts with the argument `--delete-access-point-root-dir=false`

**Additional context**
Tested with the following setup
EKS: 1.27
EFS add-on: v1.5.8-eksbuild.1
Node group: BOTTLEROCKET_x86_64, 1.14.3-764e37e4, No Fargate nodes present

**Comment by dims** [comment]
@kordian2k the EFS CSI Driver is based off of the upstream kubernetes community repository here - https://github.com/kubernetes-sigs/aws-efs-csi-driver, So can you please raise this issue there?

**Comment by kordian2k** [comment]
@dims it seems the problem is within the issue not in the upstream driver. The latter works with the `deleteAccessPointRootDir ` flag if installed via the helm chart.

**Comment by mikestef9** [comment]
We are working on fix which will be deployed with version 1.6 of add-on

**Comment by shandr** [comment]
@mikestef9 , I'm on v1.7.0-eksbuild.1 version, and it's still not working.

**Comment by kordian2k** [comment]
I can confirm that the issue is still not resolved on 1.7.0.

**Comment by relaxdiego** [comment]
This bug is still present in `v1.7.1-eksbuild.1`

**Comment by tsoe77** [comment]
The issue still exists in `v1.7.4-eksbuild.1`

**Comment by vijaybandari** [comment]
Looking at the helm chart the value is defined under `controller` [object](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/values.yaml#L64), but the add-on configuration schema doesn't have it under `controller`, rather it's at root level ([deleteAccessPointRootDir](https://gist.github.com/vijaybandari/b91cb8ec984f755367d9ca9cd0441e5d#file-efs-json-L44)).

Fixing configuration schema should fix this.

**Comment by DrVaskee** [comment]
Still present in `v1.7.5-eksbuild.2`

We also have a lot of access points that should have been deleted a long time ago.

**Comment by mjsoyeon** [comment]
Closing the issue as this issue has been fixed in latest version of driver(v1.7.6)
