### ISSUE TITLE
[ECR] [request]: Turn on scan-on-push by default via AWS Organizations

### ISSUE THREAD

**Issue by anupwarrier** [aws/containers-roadmap#799]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Turn on scan-on-push by default via AWS Organizations

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Since ECR scan on push was announced, customers have been asking their internal teams to enable this feature for new and existing repos, and realizing there are hundreds of opportunities to turn this on, but lacking a good way to guide teams to do this automatically going forward.
Could this be an option in Organizations, to turn on scan-on-push by default?

**Are you currently working around this issue?**
How are you currently solving this problem?

Can think of a periodic lambda, but not an ideal solution.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by rpnguyen** [comment]
@community: We're looking for input on this proposal.

One way to think about this is being able to configure a "repository creation template" similar to EC2 Launch Configurations. Would this kind of thing help make using ECR easier?

**Comment by jwenz723** [comment]
It would be useful to be able to have multiple 'defaults' defined and applied to repositories that match a regex or some sort of pattern. This way you could define a repository naming standard per team (like `teama-*` and `teamb-*`) and apply a different set of defaults per team.

**Comment by soapergem** [comment]
Our team would have loved this feature to already be implemented and I'm pretty disappointed that it's been sitting out here as an open Github issue for over a year. We're using one central ECR registry within one  AWS account, while we have many applications built and running in multiple other AWS accounts who publish to (and then pull from) this central registry.

I had hoped we could simply codify the cross-account access in Terraform but this is only partially true. We can configure a policy on the registry to allow other AWS account principals to create new repositories, but we can't codify a default repository policy for those newly created ECR repos. This is a feature that is sorely missing right now.

So instead, we've built custom tooling into our CI/CD system to apply a policy template any time a new repository is created. But it doesn't feel great having to essentially hard-code policies within CI/CD build tools. It would be much more aligned with all our other codification of infrastructure if we could simply define the default repository permissions through Terraform as well.

**Comment by MiGrandjean** [comment]
FTR: The mentioned use-case in #1188 is also quite important to us:

> **Tell us about your request**
> Add support for having global/default lifecycle policies which applies to all the repositories in a region or even better if it supports filters based on repo prefix.
> 
> **Which service(s) is this request for?**
> ECR
> 
> **Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
> Setting up the same policies again and again for each new repository we create feels cumbersome.

 Being able to add default or global ECR lifecycle policies would safe us from having to write our own clean-up tooling.

**Comment by hsejour** [comment]
Hi All, we are working on a feature that would address this. We'll provide an update on the progress at a later date.

**Comment by brittandeyoung** [comment]
@hsejour Any update on this? is it still a Work in Progress? Being able to set lifecycle settings for all repositories would be very helpful.

**Comment by ecarmen16** [comment]
Yup - we're looking at deprecating a years old Lambda that does this for ECR policies and it would suck to take a step backwards. Baffling this still doesn't exist.

**Comment by caretak3r** [comment]
4 years later and this still hasn't been addressed or talked about...

**Comment by samkearney** [comment]
@caretak3r It was addressed and talked about 10 months ago: https://github.com/aws/containers-roadmap/issues/799#issuecomment-1611600453

The assignment changed 5 months ago

**Comment by mikestef9** [comment]
We launched repository creation templates last year, which addresses most of the asks here 

https://aws.amazon.com/about-aws/whats-new/2024/07/amazon-ecr-repository-creation-templates-generally-available/

Will leave this issue open, as we plan to use repository creation templates for create on push functionality.

**Comment by Quanalogy** [comment]
@mikestef9 Creation templates are not addressing the ongoing maintenance of a repository, this is obviously something you should manage from the registry rather than on each individual repository.
It is a good idea to find a way where this registry could get more dynamic and using creation template for that might make sense, however ongoing maintenance of what is made is still not addressed by this and implementing lambdas to do that is simply lackluster as compared to any other container registry.

I think AWS can do better on this point.
